version: '3.1'

services:

  mariadb:
    image: mariadb
    restart: always
    ports:
      - 11001:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - apps/mariadb:/var/lib/mysql
    



  postgres:
    image: postgres:14-alpine
    ports:
      - 11002:5432
    volumes:
      - apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db


  mysql:
    image: mysql:8.0
    ports:
      - 11003:3306
    volumes:
      - apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_USER=citizix_user
      - MYSQL_DATABASE=citizix_db
      - MYSQL_PASSWORD=S3cret


