version: '3.1'
name: astproject

services:
  postgres:
    image: postgres
    container_name: ast_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    volumes:
      - ./dbdata/postesql:/var/lib/postgresql/data
    ports:
      - 11003:5432
  clickhouse:
    image: clickhouse/clickhouse-server
    user: "101:101"
    container_name: ast_clickhouse
    volumes:
      - ./dbdata/clickhouse-server/config.d/:/etc/clickhouse-server/config.d/
      - ./dbdata/clickhouse-server/users.d:/etc/clickhouse-server/users.d/
    ports:
      - 8123:8123
      - 9000:9000
