version: '3.8'
name: astproject

services:
  postgres:
    image: postgres
    container_name: ast_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - 11003:5432

  clickhouse:
    image: clickhouse/clickhouse-server
    user: '101:101'
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ./clickhouse/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - 8123:8123
      - 9000:9000
      - 9004:9004
      - 9005:9005
